#permalink: /:year/:month/:day/:title.html
permalink: /:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 陈艺夫
  email: qijunmi@163.com
  link: http://qijunmi.github.io
# weibo: http://weibo.com/yansu0711
  github: http://github.com/qijunmi

# 站点信息
title: A Blog of Qijunmi 
description: Tech Blog of Qijunmi
url: http://qijunmi.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: asset/pic/avatar.png 
favicon: asset/pic/avatar.png 

# google analytics 设置
ga:
  id: UA-43667383-1
  url: qijunmi.github.io

# disqus 设置
disqus:
  shortname: nemax 

#duoshuo评论设置
comments:
  provider : duoshuo
  duoshuo:
    short_name: forlzjava

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
#cates: 
#  - Python
#  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
